Authentication
Farida-Hamid/BlogApp pull request #9
Opened 2022-12-22 16:54 UTC by Farida-Hamid

### Steps:
- Remove current_user method in ApplicationController
- Install and setup devise.
- Can register a new user.
  - User logs in with a combination of email and password.
  - Hashed password should be stored in the database.
  - Ask for confirmation of email.
  - Can reset password.
- Modify the views in devise for registration and login to match the wireframes from the Sneak Peek and styling.

2022-12-22 17:38 UTC, FrederickMih requested changes
## Hi :raising_hand:  @Farida-Hamid, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Screenshot from 2022-10-20 09-38-51](https://user-images.githubusercontent.com/63087491/209193374-757991bd-d0a0-4253-b1fd-174c2078dc23.png)



## Highlights

- Great commit history :heavy_check_mark: 
- PR is professional :heavy_check_mark: 
- The views in devise for the registration and login have been modified :heavy_check_mark: 
- All Linter checks passed :heavy_check_mark: 


## Required Changes ♻️
N/A
_Check the comments under the review._

## Optional suggestions
N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-22 17:38 UTC, FrederickMih commented on app/views/devise/registrations/new.html.erb
> +<%= render "devise/shared/links" %>
- [ ] Hi @Farida-Hamid, I got the console error on the screenshot below when I tried to register as a new user into your app. Let's kindly figure out the issue and fix :wrench: it.


![Screenshot from 2022-12-22 18-22-56](https://user-images.githubusercontent.com/63087491/209191258-5c040cd7-21ec-4911-8d79-fe19f73810f7.png)

2022-12-23 08:54 UTC, VICTOR-CHUKWU requested changes
Hi @Farida-Hamid , 
## STATUS: CHANGES REQUIRED :recycle: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-12-23 08:54 UTC, VICTOR-CHUKWU commented on app/views/devise/registrations/new.html.erb
> +      <%= f.submit "Sign up" %>
- [ ] sign up button is not clicking with an error in d console, kindly fix this
![Screenshot from 2022-12-23 09-50-47](https://user-images.githubusercontent.com/66097371/209304763-fb8a12e3-3145-4ae6-838a-84fabda8f337.png)

2022-12-23 10:33 UTC, Nemwel-Boniface approved these changes
## Hello @Farida-Hamid           :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for meeting all the project requirements good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-23 10:34 UTC, merged